### PR TITLE
Update image package version to 4.0.8

### PR DESCRIPTION
**Pull request by ravikant-paudel**
This PR consist fix for #442

### CODE REVIEW

**Comment by mark8044** [comment]
I think you should take image up to 4.0.10

**Comment by ravikant-paudel** [comment]
> I think you should take image up to 4.0.10

ok let me add

**Comment by ravikant-paudel** [comment]
> Why did this PR still not merge? Is there some problem with it?

waiting for review.

**Comment by MarkOSullivan94** [comment]
Closing this as we've updated dependencies in this PR: https://github.com/fluttercommunity/flutter_launcher_icons/pull/447

**Pull request closed without merging**
