### PR TITLE
feat: added support for android 13+ themed icons

### LINKED ISSUE #419: [FEATURE REQUEST] Support for android 13 themed icons
Is it possible to add support for themed icons in android 13 by adding an additional monochrome icon version as a separate asset field?

### LINKED ISSUE #458: [FEATURE REQUEST] Android 13 themed icons
### :speech_balloon: Description
Please add support for themed icons

### :question: Platform
Is this feature request for a specific platform? Android

### PR DESCRIPTION
**Pull request by OutdatedGuy**
## New

- Added support for [Android 13+ Adaptive Monochrome/Themed Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming) using the `adaptive_icon_monochrome` key in config.

## Changes

- Changed logic of how mipmap xml file is created to be more readable and concise.

closes #458; closes #419;

### CODE REVIEW

**Comment by OutdatedGuy** [comment]
Hi @MarkOSullivan94, can you review this PR and tell me if changes are needed.

**Review by MarkOSullivan94 — APPROVED** [review]
Great addition! 🥳

**Comment by MarkOSullivan94** [comment]
@OutdatedGuy this is a major new feature for flutter_launcher_icons and with it I'm happy to see us make a new release for it so people can try out

**Comment by jennie-metacast** [comment]
Very excited about this feature - any idea of the time frame for releasing it? Thanks!

**Comment by josh-burton** [comment]
> Very excited about this feature - any idea of the time frame for releasing it? Thanks!

In the meantime, you can use the latest master version:

```
  flutter_launcher_icons:
    git: git@github.com:fluttercommunity/flutter_launcher_icons.git
```

**Comment by Jan10** [comment]
> Merged but not availabe via pub.dev ?

It's blocked by #224 see #220

**Pull request merged**
