### PR TITLE
Release/v0.10.0

### PR DESCRIPTION
**Pull request by RatakondalaArun**
Updated 
- Package version
- README.md
- CHANGELOG.md
- default_example

### CODE REVIEW

**Comment by RatakondalaArun** [comment]
@MarkOSullivan94 add any missing CHANGELOG items or mentions 🎉

**Comment by p-mazhnik** [comment]
Hi @RatakondalaArun ! 
I think I found an issue that can block this release -- I can't run script without having `flutter_launcher_icons.yaml`.

It seems that the reason for this is in the following code:
https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/lib/main.dart#L184
```
// Try pubspec.yaml for compatibility
    if (configFile == null) {
      try {
        return loadConfigFile('pubspec.yaml', fileOptionResult);
      } catch (_) {}
    }
```
`configFile` can't be `null`, because it has `defaultConfigFile` as a default value.

As as result, I always get `NoConfigFoundException` without `flutter_launcher_icons.yaml` file.

**Review by MarkOSullivan94 — CHANGES_REQUESTED** [review]
The issue brought up by @p-mazhnik needs to be address

**Review by MarkOSullivan94 — APPROVED** [review]
LGTM 👍

**Comment by MarkOSullivan94** [comment]
@RatakondalaArun I won't be online much over the next couple of days, if you will be and are happy to fix any bugs following the release you can feel free to publish a new GitHub release which should *hopefully* ( 🤞 ) upload a new version to Pub.

If that fails, I can upload a new version next week.

**Comment by RatakondalaArun** [comment]
But each PR requires approval is there a way to override that?

**Pull request merged**
