### PR TITLE
Update ios.dart

### PR DESCRIPTION
**Pull request by awkaw**
Add icons: 50, 57, 72

### CODE REVIEW

**Comment by mclark4386** [comment]
need to update the tests, please.

**Comment by MarkOSullivan94** [comment]
Thanks for this @awkaw! Updated one of the unit tests to ensure they were no longer failing with your changes

**Comment by delay** [comment]
These new sizes give me an error when building.  'The app icon set 'AppIcon' has 6 unassigned children.  I don't think iOS uses these sizes for apps anymore.

**Comment by awhitford** [comment]
@awkaw Can you comment as to why these sizes were added because many are now lobbying to remove them because Xcode complains about these _6 unassigned children_ and the sizes were removed from Apple's guidelines, as reported in issue #153.

**Pull request merged**
