### PR TITLE
Adding background color for iOS icon.

### PR DESCRIPTION
**Pull request by edufolly**
Adding background color for iOS icon using the `adaptive_icon_background` parameter value.

### CODE REVIEW

**Comment by aytunch** [comment]
Hi will this be added to the plugin and is there an eta? Thank you.

**Comment by edufolly** [comment]
PR updated.

**Review by VeyselSahn — APPROVED** [review]

**Comment by OutdatedGuy** [comment]
@edufolly, this feature is already present with the `background_color_ios` key in config.

It is not documented tho, hence I have raised a [issue](https://github.com/fluttercommunity/flutter_launcher_icons/issues/498) to follow up.

**Comment by SoftwareLogico** [comment]
For me is still not working
`
  flutter_launcher_icons: ^0.13.1


  flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    remove_alpha_ios: true
    background_color_ios: "#ffffff"
    adaptive_icon_background: "#ffffff"
    image_path: "assets/logo.png"
    min_sdk_android: 26
`

I did 
flutter clean
flutter pub get
flutter pub run flutter_launcher_icons
then 
flutter pub run flutter_launcher_icons:main

i deleted manually the ios icons and nope

still black background

**Comment by OutdatedGuy** [comment]
@SoftwareLogico, that's odd. I just tried after reading your comment and it worked for me.



<details><summary>Config File</summary>

```yaml
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

# dart run flutter_launcher_icons
flutter_launcher_icons:
  ios: true
  image_path_ios: "assets/icons/adaptive-icon-foreground.png"
  remove_alpha_ios: true
  background_color_ios: "#4169e1"

``` 

</details> 

| Adpative Icon | Result |
|--------|--------|
| tmp-49743-yPETPCkeAFHP- | Icon-App-1024x1024@1x |

**Comment by SoftwareLogico** [comment]
> @SoftwareLogico, that's odd. I just tried after reading your comment and it worked for me.
> 
> Config File
> Adpative Icon	Result
> tmp-49743-yPETPCkeAFHP-	Icon-App-1024x1024@1x


https://github.com/fluttercommunity/flutter_launcher_icons/assets/116231978/216e8c48-4e31-4624-90ce-0f6cfcd31fdf

**Comment by SoftwareLogico** [comment]
> @SoftwareLogico, that's odd. I just tried after reading your comment and it worked for me.
> 
> Config File
> Adpative Icon	Result
> tmp-49743-yPETPCkeAFHP-	Icon-App-1024x1024@1x


https://github.com/fluttercommunity/flutter_launcher_icons/assets/116231978/fe5ef317-f137-4898-a8d6-8bc632a62c21

Maybe I'm missing some extra step?

**Comment by OutdatedGuy** [comment]
@SoftwareLogico, can you send the image and the config you are using to create iOS icons.

**Comment by SoftwareLogico** [comment]
> @SoftwareLogico, can you send the image and the config you are using to create iOS icons.

sure
logo is just a free transparent png
logo

and config idk if you meant this:

`name: rpf
description: rpf.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.0
  flutter_native_splash: ^2.3.0
  url_launcher: ^6.1.11
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  intl: ^0.18.0
  image_picker: ^0.8.7+5
  audioplayers: ^4.1.0
  flutter_tts: ^3.7.0

flutter_native_splash:
  fullscreen: true
  android: true
  ios: true
  color: "#303236"
  image: assets/splash768.png
  android_12:
    color: "#303236"
  android_gravity: fill_horizontal|fill_vertical
  ios_content_mode: scaleAspectFit

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#585858"
  adaptive_icon_background: "#585858"
  image_path: "assets/logo.png"
  min_sdk_android: 26

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/`

**Comment by OutdatedGuy** [comment]
@SoftwareLogico ohh I realised I was using the version directly from git. Hence was getting this **_yet to be released feature_**.

Sorry for the confusion.

@MarkOSullivan94, please release a new version with latest features.

**Comment by SoftwareLogico** [comment]
> @SoftwareLogico ohh I realised I was using the version directly from git. Hence was getting this **_yet to be released feature_**.
> 
> Sorry for the confusion.
> 
> @MarkOSullivan94, please release a new version with latest features.

Oh don't worry, i'm glad you took the time to check that out. I appreciate it😊

**Review by erperejildo — APPROVED** [review]

**Comment by MarkOSullivan94** [comment]
Outdated and should be working now with `background_color_ios`

**Pull request closed without merging**
