### PR TITLE
Added a sample app that supports flavors

### PR DESCRIPTION
**Pull request by jorgecoca**
## In iOS

Screen Shot 2020-02-06 at 11 11 02 AM

## In Android

Screen Shot 2020-02-06 at 11 17 46 AM

### CODE REVIEW

**Comment by edgarfroes** [comment]
@MarkOSullivan94 and @slightfoot would you guys mind? This is an awesome addiction to this plugin and people need it :)

**Comment by MarkOSullivan94** [comment]
Tested it both `production` and `development` flavours on an Android emulator and it worked fine for me!

Only slight tweak I'd like to see is for the flavors sample app to be included within the example directory and the existing example to be moved to a `default` directory, so the structure should be like the following:

`...example/default/...`
`...example/flavors/...`

Once that change is made, I'm happy to merge 👍

**Comment by jorgecoca** [comment]
@MarkOSullivan94 I just pushed the changes ;)

**Comment by ozasadnyy** [comment]
@MarkOSullivan94 are you ready to merge this request?

**Comment by MarkOSullivan94** [comment]
Hoping I'll get a chance to review this PR in more depth late tomorrow evening if not late Sunday evening / Monday

**Pull request merged**
