### PR TITLE
Added missied sizes for iOS

### PR DESCRIPTION
**Pull request by bossly**
Screenshot 2021-11-04 at 23 04 44

### CODE REVIEW

**Comment by bossly** [comment]
@abraham @sestegra @brianegan @shinriyo can anyone approve that?

**Comment by bradintheusa** [comment]
Taking a look.

**Review by bradintheusa — APPROVED** [review]
This looks good. I see no reason to hold up.

**Review by RatakondalaArun — APPROVED** [review]
LGTM

**Review by RatakondalaArun — CHANGES_REQUESTED** [review]
This PR is failing two tests in `tests/main_test.dart`

```shell
$ flutter test test/main_test.dart
Running "flutter pub get" in flutter_launcher_icons...             10.9s
00:08 +0 -1: iOS icon list is correct size [E]
  Expected: <15>
    Actual: <21>

  package:test_api          expect
  test\main_test.dart 14:5  main.<fn>

00:08 +1 -2: iOS image list used to generate Contents.json for icon directory is correct size [E]
  Expected: <19>
    Actual: <25>

  package:test_api          expect
  test\main_test.dart 24:5  main.<fn>

00:08 +13 -2: Some tests failed.
```

Please update this tests

**Comment by bossly** [comment]
> This PR is failing two tests in `tests/main_test.dart`
> 
> ```shell
> $ flutter test test/main_test.dart
> Running "flutter pub get" in flutter_launcher_icons...             10.9s
> 00:08 +0 -1: iOS icon list is correct size [E]
>   Expected: <15>
>     Actual: <21>
> 
>   package:test_api          expect
>   test\main_test.dart 14:5  main.<fn>
> 
> 00:08 +1 -2: iOS image list used to generate Contents.json for icon directory is correct size [E]
>   Expected: <19>
>     Actual: <25>
> 
>   package:test_api          expect
>   test\main_test.dart 24:5  main.<fn>
> 
> 00:08 +13 -2: Some tests failed.
> ```
> 
> Please update this tests

fixed

**Review by RatakondalaArun — APPROVED** [review]
LGTM

**Pull request merged**
