### PR TITLE
Read flavor icons files

### LINKED ISSUE #54: Flavors?
It would be nice to have the possibility to use this package also to manage various flavors icons, I guess this might be a breaking change to simply replicate this configuration API.
Another option would be making a new package, some type of flavors helper which uses this package to handle the icon parts.

### PR DESCRIPTION
**Pull request by sestegra**
Expected files are following:
- `flutter_launcher_icons.yaml` or `pubspec.yaml` from default icons
- `flutter_launcher_icons-<flavor>.yaml` for flavor icons

TODO
- [X] Android support
- [X]  iOS support
- [X] Fix #54

### CODE REVIEW

**Comment by sestegra** [comment]
iOS configuration should be suffixed by `-<flavor>`. (e.g. `Release-prod`)

**Comment by MarkOSullivan94** [comment]
Hey @sestegra thank you for this PR! 

Apologies for the delayed response, took time off over the holiday season. Wanted to reply to this PR and acknowledge your great efforts with this, I know it had been requested in the past.

I'll need to test this before merging it in. Schedule is a bit busy atm so can't give you an estimation on when I'll get it done.

I know two users posted about the flavours idea so going to ping them in case they're interested in testing it out to help speed up the process @rockneverdies55 @GregorySech

**Comment by GregorySech** [comment]
Yeah, I'll be checking it out this week (probably in the weekend)

**Comment by sestegra** [comment]
I pushed updates for points 1 & 2.
For unit tests, only the existence of flavor file(s) could be tested, but I busy on the next couple weeks.

**Comment by MarkOSullivan94** [comment]
Hi @sestegra! Appreciate you pushing your updates.

I tried testing out your changes but I was receiving the below error message when I changed my Android run configurations to run the x build  flavor.

```
The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file does not define any custom product flavors.
You cannot use the --flavor option.
Finished with error: Gradle build aborted.
```

Curious if this PR will only work on a project which currently has flavors working for both the iOS and Android Flutter app?

If so, it would be best updating the example project so it can be run with the different flavours.

**Comment by sestegra** [comment]
In fact, I have only tested the icons build, not the app itself.

See a full project example [here](https://github.com/sestegra/flutter_assets_flavors)
I'm using a script to create flavors.

**Comment by MarkOSullivan94** [comment]
Okay so I've tested it out in your example project and it seems to be working fine there. However I do think an example within Flutter Launcher Icons would be good.

I believe the example directory should be updated to contain two example apps: 

1. Default 
2. Flavors

Mainly because flavors seems to be pretty unique compared to the other features and I don't want people getting confused thinking they need all the different configuration files to quickly change the default Flutter app icons.

For now I'm happy to merge flavors into it's own branch until I get the example directory updated and then merge in the flavor support along with the example app showing how it works.

**Comment by sestegra** [comment]
In fact, as you suggest, it's better to avoid confusion
- to keep default icon generation as the main solution
- to keep flavoring as an advanced and optional feature: for instance, create a seperated README

**Comment by Muldec** [comment]
Any chance to see this PR merged into master any time ?

**Comment by PandaGeek1024** [comment]
any updates on this?

**Pull request merged**
