### PR TITLE
Feature: Configure dark and tinted mode icons for iOS 18+

### PR DESCRIPTION
**Pull request by KevinHaendel**
This PR adds the ability to set the new dark and tinted mode icon images for iOS 18+. This PR includes:

- Setting a dark mode app icon for iOS 18+
- Setting a tinted mode app icon for iOS 18+

(Both according to [Apples Human Interface Guidelines for App Icons](https://developer.apple.com/design/human-interface-guidelines/app-icons#iOS-iPadOS)
- Automatically desaturate tinted mode app icon image if configured
- Refactor generation of Contents.json file
- Add description of added properties and modified template file

### CODE REVIEW

**Review by TilDoesCode — APPROVED** [review]

**Comment by TilDoesCode** [comment]
Why isnt this merged yet?

**Comment by lsrmg** [comment]
iOS 18 is dropping in a couple of days. That would be great to have!

**Comment by TilDoesCode** [comment]
@lsrmg especially since its ready, and from what I can tell, working already

**Comment by MarkOSullivan94** [comment]
@KevinHaendel huge thank you for this 

@TilDoesCode I'm going to assume you've tested this, I haven't had a chance to just yet but I'll be releasing an iOS app in the coming weeks so I'll have a chance to double check this later

**Review by MarkOSullivan94 — APPROVED** [review]

**Comment by harishsaini** [comment]
how to make this work? 
simply adding this does not work
```
  image_path_ios_dark_transparent: assets/launcher/common_launcher_dark.png
  image_path_ios_tinted_grayscale: assets/launcher/common_launcher_dark.png
```

**Pull request merged**
